### ISSUE TITLE
[BUG] Arm Extender displays as craftable, but can't be crafted

### ISSUE THREAD

**Issue by klassekatze** [itsdinkd/AQM2#87]
**Modpack Version**
1.5

**Minecraft Version**
1.18.2

**Describe the crash or bug**
The Arm Extender fails to craft using the recipe shown ingame with REI, instead dumping ingredients.

**Steps to reproduce the behavior:**
Place 2 perilyo rod, xenon rod, brass hand, gleaming compound matching REI shown pattern in Create mechanical crafter array and let it run.

**Expected behavior**
It should give me an Arm Extender! :P

**Screenshots**
N/A - it'd just be items in the grid or on the ground.

**Crash log or latest.log.log**
N/A

**Additional context**
From looking at kubejs\server_scripts\balance.js , it appears that there is actually another ingredient defined, "c:ingots/fiery". Cursory googling suggests this is from Twilight Forest, which isn't in the pack at the moment. That would explain why it wouldn't show in the recipe in REI, yet the crafter knows only that something with that tag isn't there, and thus doesn't recognize a match for the Arm Extender.

I speculate "c:ingots/fiery" should be replaced or removed in the recipe defined in balance.js to make the Arm Extender craftable.

**Comment by klassekatze** [comment]
err, Arm Extender, not Extendo Grip. whatever you know what I meannnn

**Comment by itsdinkd** [comment]
Fixed, thanks for the report

**Comment by Nvggs** [comment]
I am still having this issue, I had it when the recipe didn't include a lead ingot. Yet even after updating to the new recipe, the items just drop onto the floor
